### ISSUE TITLE
Error TS1086: An accessor cannot be declared in ambient context.

### ISSUE THREAD

**Issue by josel567** [louy/typed-sequelize#184]
Hi everyone, I have a proyect that shows this error when I run 'tsc':

```
 ../../node_modules/sequelize/types/lib/transaction.d.ts(33,14): error TS1086: An accessor cannot be declared in an ambient context.
../../node_modules/sequelize/types/lib/transaction.d.ts(40,7): error TS1086: An accessor cannot be declared in an ambient context.
```
My versions are:
- "@types/sequelize": "^4.28.6"
- "sequelize": "^5.8.10"
- "sequelize-typescript": "1.0.0-beta.4"

The proyect works fine with nodemon but fails when I try to compile the typescript. Anyone knows this error?

Thanks.

**Comment by louy** [comment]
I don't think this is the right repo. The error you mentioned comes from the types that are shipped with sequelize itself. I recommend filing an issue on https://github.com/sequelize/sequelize

**Comment by louy** [comment]
FWIW looks like your version of typescript might be out of date. it looks like this error happens when using code written for typescript@3.7 with an older version of the compiler

https://github.com/aws-amplify/amplify-js/issues/4389
