### ISSUE TITLE
belongsToMany returns void

### ISSUE THREAD

**Issue by felixfbecker** [louy/typed-sequelize#2]
If you look at the source code, belongsToMany actually [returns an association object](https://github.com/sequelize/sequelize/blob/master/lib/associations/mixin.js#L267) that represents the association. [It is recommended to save this object to pass it to the `include` option of the find methods](https://github.com/sequelize/sequelize/issues/5215#issuecomment-171571661).

This also applies to hasMany and belongsTo

**Comment by louy** [comment]
I didn't know that. I pass the related model to the `include` option instead.
Anyway, #3 should've fixed this I believe.
Thanks btw!

**Comment by felixfbecker** [comment]
@louy `typings install sequelize` still gives me the old definition, do you need to publish this or something?
