### ISSUE TITLE
[v4] Is it possible to use sequelize.define method?

### ISSUE THREAD

**Issue by piteer1** [louy/typed-sequelize#59]
Hi,

I was trying to use Sequelize define method instead of Model.init(), but I cannot find a proper way to use it.  I was trying to do it this way:

```typescript
import { DataTypes, Model, ModelAttributes, ModelAttributeColumnOptions } from 'sequelize';
import sequelize from '../sequelize';//connection

class MyModel extends Model {
  id: string;

  foo() {}
}

const type = sequelize.define<MyModel>('MyModel', <ModelAttributes>{
  id: <ModelAttributeColumnOptions>{
    type: DataTypes.UUIDV4,
    primaryKey: true,
  },
});

type.findById('id'); // this causes transpilation error
```
 
According to typings define method returns an instance of type `TModel` not the `TModel` type itself, so it's impossible this way to use any of the static methods defined in `Model` class. Is it possible to use this method at all, or it's currently required to use only ```Model.init()``` method?

Changing the typing to ```define<TModel>(...): typeof Model``` would allow access to `Model` static methods but at the same moment it would make impossible to access any of the `MyModel` attributes. Probably the easiest way would be making this function to return `typeof TModel` but it didn't seem to be possible with TypeScript. Is any workaround for this?

Best

**Comment by felixfbecker** [comment]
It doesn't make much sense to declare a class just for the type if you're not gonna use it, you should use interfaces. One possible way is shown in the tests: https://github.com/louy/typed-sequelize/blob/master/4/test/define.ts

**Comment by felixfbecker** [comment]
If you want to use a class to type it, you need to pass `typeof MyModel` as the type parameter or you will get an instance back.

**Comment by piteer1** [comment]
@felixfbecker I should have firstly take a look into the tests directory... Thanks for the answer and yeah, it looks much better when using classes with `init` instead of `define`. I was hoping to achieve something like:
```typescript
const myType = define<typeof MyModel>(...)

const inst1: MyModel = myType.findById('1');

const inst2: MyModel = new myType();
inst2.id;
```

Still this way I would have to export two things from a module to define a variable type somewhere else in a code

```typescript
export default myType;
export { MyModel }
```

Thanks for help

**Comment by felixfbecker** [comment]
No problem. Is there any reason you want to use `define()`? All it does is create a class for you: https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L343-L355

**Comment by piteer1** [comment]
No, there's no particular reason for it. I think using `define` is the most common way to define a model with Sequelize in JS, so I wanted it to be similar in TypeScript.
